---
title: "Inhibitory_edges"
author: "Chenxin Li"
date: "2022-12-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages
```{r}
library(tidyverse)
library(igraph)
library(ggraph)
library(ggarrow)

library(readxl)

library(viridis)
library(RColorBrewer)
library(rcartocolor)
```

# Linear pathway 
##  Data
```{r}
Et_signaling <- read_excel("../Data/Et_signaling_edges.xlsx")
head(Et_signaling)
```
## Network object 
```{r}
Et_signaling_pathway <- graph_from_data_frame(
  d = Et_signaling,
  directed = T
)
```

## Extract XY coordinates
```{r}
xy <- ggraph(Et_signaling_pathway, layout = "tree")$data %>% 
  select(x, y, name)
xy
```
## Generate the edge data frame with start and end coordinates 
```{r}
Et_pathway_edges <- Et_signaling %>% 
  mutate(edge_id = paste0(From, "-", To)) %>% 
  mutate(From = as.character(From)) %>% 
  mutate(To = as.character(To)) %>% 
  inner_join(xy, by = c("From" = "name")) %>% 
  rename(
    temx = x, 
    temy = y,
  ) %>% 
  inner_join(xy, by = c("To" = "name")) %>% 
  rename(
    x = temx,
    y = temy,
    xend = x,
    yend = y
  )

Et_pathway_edges
```
## Make Diagram
```{r}
Et_pathway_edges %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point(data = xy,
             aes(x = x, y = y),
             size = 2) +
  geom_label(data = xy,
            aes(label = name, x = x), size = 4, hjust = -0.1) +
  geom_arrow_curve(aes(arrow_head = Sign, color = Sign,
                       xend = xend, yend = yend+0.1), linewidth = 1.1, alpha = 0.8) +
  scale_arrow_head_discrete(values = list(
   arrow_head_wings(offset = 30, inset = 70),
   arrow_head_line(90, lineend = "round")
  )) +
  scale_x_continuous(limits = c(-0.1, 0.2)) +
  scale_color_manual(values = c("tomato1", "grey20")) +
  labs(arrow_head = "",
       color = "",
       title = "Ethylene signaling pathway") +
  theme_void() +
  theme(legend.position = c(0.75, 0.5)) 

ggsave("../Results/Ethylene_Signaling_pathway.svg", height = 4, width = 3, bg = "white")
ggsave("../Results/Ethylene_Signaling_pathway.png", height = 4, width = 3, bg = "white")
```





 

